### ISSUE TITLE
Exception from accessing blog url when there is only one blog

### ISSUE THREAD

**Issue by bingxie** [comfy/comfy-blog#32]
I only create one blog. And access the URL like this: http://localhost:3000/mxc/blog/market

There is a exception like this:

ComfortableMexicanSofa::MissingPage in Comfy::Blog::PostsController#serve
Cannot find CMS Page at /404

Rails.root: /Users/bing/Codes/comfortable-mexican-sofa-with-blog

Application Trace | Framework Trace | Full Trace
Request

Parameters:

{"cms_path"=>"",
"slug"=>"market"}

**Comment by GBH** [comment]
`serve` action is gone. There's only one blog per site now.
