### ISSUE TITLE
New comfy_paginate wrapper

### ISSUE THREAD

**Issue by thealtair** [comfy/comfy-blog#38]
I'm using Comfy CMS and Comfy Blog, both at latest (1.12.4, 1.12.2) and it looks like the blogs non-admin posts_controller could use the 'comfy_paginate' helper, but because comfy_paginate is defined in Comfy CMS's Admin Base Controller, the paginate helper wouldn't be available to the non-admin blog base controller.

Now I do understand that this wrapper is barely a week old, so I was wondering if this is a good addition, or is there a reason the wrapper is solely limited to admin controllers? I'm more than happy to help with anything needed.

**Comment by GBH** [comment]
I think it's my bad. Technically it's expected that you'll be non-admin views with your own. Then you can do pagination with will_paginate or kaminari (none of those are shipped with CMS now)

**Comment by thealtair** [comment]
Oh! I'm so sorry. I just realized that! I need to add WillPaginate or Kaminari to my own Gemfile. Thanks for clearing that up.
