### ISSUE TITLE
undefined method `comfy_paginate' for Comfy::Admin::Blog::BlogsController#index

### ISSUE THREAD

**Issue by jpbullalayao** [comfy/comfy-blog#39]
I installed the latest gem for comfy-blog, and as I'm trying to access the 'Blogs' link in the admin page, I immediately get this undefined error. It seems that the latest gem is using `comfy_paginate`, but it's not defined anywhere? How do I get around this?

**Comment by jpbullalayao** [comment]
My apologies if this is a quick fix; I'm still learning Rails haha!

**Comment by GBH** [comment]
I might've messed up gemspec. Make sure you also have 1.12.4 version of CMS

**Comment by jpbullalayao** [comment]
Ahh that did it, I was on the 1.12.3 version of the CMS. Thanks for the quick response!
