### ISSUE TITLE
Front end post pagination url

### ISSUE THREAD

**Issue by goreblimey** [comfy/comfy-blog#43]
The url constructed for blog post pagination contains a duplicate blog name leading to an incorrect url.

For example the following is generated...

http://comfy-demo.herokuapp.com/blog/blogado/blogado?page=2

I think it should be (without the extra '/blogado')

http://comfy-demo.herokuapp.com/blog/blogado/?page=2

**Comment by joshmn** [comment]
Someone else will see this, so I'll just comment even though this is 9 months old.

In your routes, I'm assuming you left the routes default, e.g. ` comfy_route :blog, :path => '/blog'` and then when you created the blog in comfyadmin, you give it a url such as blogado

The URL hooks into comfy_route :blog's path.

**Comment by bhushangahire** [comment]
@joshmn Thanks for the comment but I am getting the same issue. I am not following your answer. Can you please give me example.
I have multiple blogs architecture
And my routes is pointed to 
`comfy_route :blog, path: 'blog'`

**Comment by GBH** [comment]
In v2.0 routes are redone and pagination doesn't generate bad links from what i can see.
