### ISSUE TITLE
Fixtures

### ISSUE THREAD

**Issue by jpbullalayao** [comfy/comfy-blog#45]
Is there way to export blog into fixtures, just like the CMS?

**Comment by GBH** [comment]
No. Why would you want that? CMS fixtures exist to make development less painful. It's not really meant to serve as a mechanism to store data. Generally, the moment you pushed everything to production it's time to delete CMS fixtures.

What's your use-case?

**Comment by jpbullalayao** [comment]
You're absolutely right, thanks for your input. I posted this issue because I pushed my project to another server and the Blog I made in development wasn't automatically imported along with the rest of the CMS stuff; but this is something that could be handled with a seed file (which I just learned about recently).

**Comment by GBH** [comment]
:+1: Seed file, or just a db dump is the way to go.
