### ISSUE TITLE
DoubleRenderError when post does not exist

### ISSUE THREAD

**Issue by psulightning** [comfy/comfy-blog#52]
```
An AbstractController::DoubleRenderError occurred in posts#serve:

  Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".
```

I think this is attributed to https://github.com/comfy/comfy-blog/blob/master/app/controllers/comfy/blog/posts_controller.rb#L16 since there is a `show && render(show)` when if the post isn't found https://github.com/comfy/comfy-blog/blob/master/app/controllers/comfy/blog/posts_controller.rb#L49-L51 rescue block fires.

**Comment by GBH** [comment]
`serve` is gone in v 2.0. Double render should not be a thing now.
