### ISSUE TITLE
error 404 in blog, works in cms

### ISSUE THREAD

**Issue by espen** [comfy/comfy-blog#57]
https://github.com/comfy/comfy-blog/blob/master/app/controllers/comfy/blog/posts_controller.rb#L50 is giving a `ComfortableMexicanSofa::MissingPage: Cannot find CMS Page at /404` for me.

404 for the CMS works fine, but not for the blog.

Should this perhaps be `rescue_from ActiveRecord::RecordNotFound, :with => :page_not_found` like in Comfy?

**Comment by espen** [comment]
Should this work the same as https://github.com/comfy/comfortable-mexican-sofa/issues/157 ? I can submit a pull request

**Comment by GBH** [comment]
While the 404 handling code didn't change much, let's close it and reopen if this is still an issue. Can't tell why 404 would work from cms pages, but not from the blog.
