### ISSUE TITLE
Comfy-Blog routes are not identited

### ISSUE THREAD

**Issue by railsfactory-bhaskararao** [comfy/comfy-blog#59]
```
 gem 'comfortable_mexican_sofa', '~> 1.12', '>= 1.12.8'
 gem 'comfy_blog', '1.12.3'
```

routes;

```
comfy_route :blog_admin, :path => '/adminblog'
comfy_route :blog, :path => '/blog'

comfy_route :cms_admin, :path => '/cms'
comfy_route :cms, :path => '/pages', :sitemap => false
```

When navigated to http://0.0.0.0:3000/adminblog

![blog_routes_not_identified](https://cloud.githubusercontent.com/assets/13519599/11760912/192c4e7e-a0d4-11e5-8fac-c72cc1f00e6b.png)

but cms working fine.
Can some tell me how to make this blog work with cms?

**Comment by GBH** [comment]
This definitely work in 2.0. Just as a note, both blog and cms can share same `/admin` path
