### ISSUE TITLE
site & blog path should be nil by default

### ISSUE THREAD

**Issue by chamnap** [comfy/comfy-blog#64]
On rails 5, when the value is empty string, it will generate `/`. If it's nil, it will generate nothing.

```
> app.comfy_blog_post_path('', '', :slug)
=> //blog//slug

> app.comfy_blog_post_path(nil, nil, :slug)
=> /blog/slug
```

On rails 4, it's different. Either empty string and nil will generate the same result.

```
> app.comfy_blog_post_path('', '', :slug)
=> /blog/slug

> app.comfy_blog_post_path(nil, nil, :slug)
=> /blog/slug
```

**Comment by GBH** [comment]
Fixed in CMS and will be fixing this in the blog. Thanks.
