### ISSUE TITLE
How to add tag and/or categories to post?

### ISSUE THREAD

**Issue by LavenderGrey** [comfy/comfy-blog#71]
I don't see how to add the tag or categories to posts.
Thank you.

**Comment by GBH** [comment]
What version of CMS are you using? 

In 2.0+ you manage categories on the right column from the Post listing view. Then you can just check categories during Post creation/editing.

**Comment by LavenderGrey** [comment]
I did new install of both comfy cms and blog. The categories don't appear on the side until after the first entry has been published. Now it shows up on the side during creation/editing. I've been playing with it awhile today and it seems all good.
