### ISSUE TITLE
NameError in Blog Posts form tab

### ISSUE THREAD

**Issue by EmanuelN** [comfy/comfy-blog#72]
### Expected behavior
Admin Blog Posts tab should open form after template has been created

### Actual behavior
Blog Posts returns Rails error 
NameError in Comfy::Admin::Blog::Posts#new
![screen shot 2018-04-10 at 2 13 30 pm](https://user-images.githubusercontent.com/9320290/38575455-71ac47d2-3cc9-11e8-98d1-45cd8d00a93e.png)

I should note that when a layout is not defined a form renders but I can't edit content (makes sense) 
![screen shot 2018-04-10 at 2 18 22 pm](https://user-images.githubusercontent.com/9320290/38575706-19656f58-3cca-11e8-98db-52deedce25b9.png)

### Steps to reproduce
Create a new Rails project
Install comfortable_mexican_sofa as per instructions
Install comfy_blog as per instructions
Start server and head to admin panel
Create a site
Create new layout with default Application layout
Click on Blog Posts in admin panel

### System configuration
**Rails version**: 5.2.0.rc2

**CMS version**: 2.0.13

**comfy-blog version**: 2.0.5

**Ruby version**: 2.5.1

**OS**: macOS High Sierra 10.13.4

**Comment by GBH** [comment]
CMS v2.0.13 did some changes to how that form is rendered and I never checked if Blog still worked. It's fixed. Grab Blog v2.0.6
