### ISSUE TITLE
Blog posts are returned unsorted from PostsController#index

### ISSUE THREAD

**Issue by kirichkov** [comfy/comfy-blog#75]
### Expected behavior
Index should return `@blog_posts` sorted according to their published date

### Actual behavior
`@blog_posts` are returned unsorted. This can result in a blog post appearing on multiple pages and others not appearing at all.

### System configuration
**Rails version**:
5.2.0

**CMS version**:
2.0.15

**Ruby version**:
2.5.1p57

**Comment by GBH** [comment]
Makes sense. PR?

**Comment by kirichkov** [comment]
Will do!
